### ISSUE TITLE
Wizard Admin Randomly Deletes all Pages of Wizard Form

### ISSUE THREAD

**Issue by rosenoam** [tsgrp/ActiveWizard#296] opened 2016-10-20 19:31 UTC
Created three page forms, activated it and published it. Form was still there and all the versions were still there but there were no pages present after logging back into Active Wizard. 

![screencapture-release2-tsgrp-wizardadmin-login-1476991693899](https://cloud.githubusercontent.com/assets/22036850/19574922/ea4d4e56-96d1-11e6-8e2f-37524725231a.png)
![screencapture-release2-tsgrp-wizardadmin-login-1476991736020 1](https://cloud.githubusercontent.com/assets/22036850/19574929/ef2eae6a-96d1-11e6-8271-e048047aa19a.png)

**Comment by gsteimer** [comment] 2017-07-19 14:43
Closing this - can't reproduce

**Closed as completed by gsteimer** 2017-07-19 14:43 UTC
Labels: wontfix
